Vagrant.configure("2") do |config|
  config.vm.define :test_vm do |test_vm|
    test_vm.vm.box = "debian/stretch64"
    test_vm.vm.synced_folder ".", "/vagrant", :type => "nfs", disabled: true
  end
end
