Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.provider :libvirt do |libvirt|
    libvirt.qemu_use_session = false
  end
  config.vm.network "public_network", ip: "192.168.122.210"
end
