Vagrant.configure("2") do |config|
  config.vm.box = "fedora/37-cloud-base"

  config.vm.provider :libvirt do |libvirt|
    libvirt.host = "lpcss"
    libvirt.connect_via_ssh = true
    libvirt.username = "libvirt"
    libvirt.socket = '/var/run/libvirt/libvirt-sock'
    libvirt.storage_pool_name = "default"
  end
end
