Vagrant.configure("2") do |config|
  config.vm.box = "centos/stream8"
  config.vm.box_url = "https://cloud.centos.org/centos/8-stream/x86_64/images/CentOS-Stream-Vagrant-8-20220913.0.x86_64.vagrant-libvirt.box"
  config.vm.synced_folder ".", "/vagrant", type: "sshfs"
end
