memory = ENV["MEMORY"] || 2048

Vagrant.configure("2") do |config|
  config.vm.box = "fedora/34-cloud-base"

  config.vm.provider :libvirt do |libvirt|
    libvirt.nested = true
    libvirt.memory = memory
  end
end
