Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.synced_folder ".", "/lizmap"

  # TODO:
  #, type: "nfs"
  #, type: "sshfs"

  config.vm.provider :libvirt do |libvirt|
    libvirt.driver = "qemu"
  end
end
