Vagrant.configure("2") do |config|
  config.vm.box = "fedora/34-cloud-base"

  config.vm.provider :libvirt do |domain|
    #domain.qemu_use_session = false
     # Add an extra disk
    domain.storage :file, :size => '20G'
  end
end
