Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.synced_folder ".", "/vagrant", type: "nfs"

  config.vm.provider :libvirt do |libvirt|
    libvirt.nested = false
    libvirt.memory = 2048
  end
end
