Vagrant.configure("2") do |config|
  config.vm.define "rawhide" do |rawhide|
    rawhide.vm.box = "fedora/37-cloud-base"

    rawhide.vm.hostname = "this.is.my.vagrant.box"

    rawhide.vm.provider :libvirt do |libvirt|
      libvirt.driver = "kvm"
    end
  end
end
